// The tool-basis normalisation (VP-I20, plan Fassungen 5–6, Codex R55/R56)
// against every consumer, on REAL payloads: one program parsed at two start
// tool offsets (scripts/test_fixtures/tool_basis_pairs.json, regenerated by
// scripts/gen_tool_basis_fixture.py with the native interpreter). The
// published payload, normalised to the other start, must give the decoded
// streams, the scrub track, the axis positions, the part-frame path, the
// scrub poses and the sweep findings of the fresh payload — in both
// directions. Without the normalisation Codex's R55 pair misses its clash.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import * as THREE from "three";
import { decodePreviewStreams, normalizeToToolBasis } from "../previewDecode";
import { buildScrubTrack, sampleTrack, type ScrubSample } from "./scrubTrack";
import { transformToPartFrame, liftToJoints, wcsTerms, tipWcs, type PartFrameMachine } from "./partFrame";
import { tloForIndex } from "./tloEvents";
import { buildCollisionModel, sweepCollisions, toolCylinderPositions, type CollisionMachine } from "./collision";

const FIXTURE = JSON.parse(readFileSync(
  resolve(__dirname, "../../../scripts/test_fixtures/tool_basis_pairs.json"), "utf8"));

// A plain XYZ machine with a fixed fixture block under the table (Codex R55).
const machine: PartFrameMachine & CollisionMachine = {
  groups: [{ id: "table", parent: "root" }, { id: "part", parent: "table" }, { id: "head", parent: "root" }],
  kinematics: [
    { group: "head", joint: 0, type: "translate", direction: "x", sign: 1 },
    { group: "head", joint: 1, type: "translate", direction: "y", sign: 1 },
    { group: "head", joint: 2, type: "translate", direction: "z", sign: 1 },
  ],
  workGroup: "part", toolGroup: "head", unitScale: 1, axes: ["X", "Y", "Z"],
};

function payloadOf(raw: Record<string, any>): Record<string, any> {
  return Object.fromEntries(Object.entries(raw).map(([k, v]: [string, any]) =>
    [k, v && v.bytes_b64 != null ? Uint8Array.from(Buffer.from(v.bytes_b64, "base64")) : structuredClone(v)]));
}

/** Everything a consumer computes from one payload decoded at `basis`
 *  (normalise = false: the payload as shipped, resolved to `basis` anyway —
 *  the R55 defect). */
function consume(raw: Record<string, any>, basis: number[], normalise = true) {
  const d = decodePreviewStreams(payloadOf(raw));
  const used = normaliseOrNot(d, raw.tlo_start, basis, normalise);
  expect(used).toEqual(basis);
  const track = buildScrubTrack(d.feed, d.rapid, d.kinsFrames, d.wcsEvents, d.subNames, d.tloEvents)!;
  const wcs = { g5x: [0, 0, 0, 0, 0, 0], g92: [], rotationDeg: 0, tool: used! };
  const joints: number[][] = [];
  for (let i = 0; i < track.count; i++) {
    const j: number[] = [];
    liftToJoints(track.pos[3 * i]!, track.pos[3 * i + 1]!, track.pos[3 * i + 2]!, 0, 0, 0,
                 wcsTerms(tipWcs(wcs)), tloForIndex(track.tlo?.[i], track.tloEvents, used), j);
    joints.push(j.map(v => Math.round(v * 1e4) / 1e4));
  }
  const path = transformToPartFrame(machine, wcs, { ...track, tloEvents: d.tloEvents });
  const box = new THREE.BoxGeometry(2, 2, 2).toNonIndexed();
  const positions = new Float32Array(box.getAttribute("position").array);
  box.dispose();
  const model = buildCollisionModel(machine, [
    { id: "fixture", group: "table", positions, translate: [5, 0, -5] },
    { id: "tool", group: "head", positions: toolCylinderPositions(6, 10), tool: true },
  ]);
  const hits = sweepCollisions(model, track, wcs, { margin: 0.1, tloEvents: d.tloEvents }).hits
    .map(h => ({ line: h.line, a: h.a, b: h.b }));
  const samples = [0, track.cum[1]! / 2, track.cum[track.count - 1]!].map(s => {
    const v = sampleTrack(track, s, {} as ScrubSample);
    const j: number[] = [];
    liftToJoints(v.px, v.py, v.pz, v.pa, v.pb, v.pc, wcsTerms(tipWcs(wcs)), v.tlo?.xyz ?? used!, j);
    return j.map(x => Math.round(x * 1e4) / 1e4);
  });
  const r4 = (a: ArrayLike<number>) => Array.from(a, v => Math.round(v * 1e4) / 1e4);
  return { pos: r4(d.feed.pos).concat(r4(d.rapid.pos)), track: r4(track.pos), joints,
           path: r4(path.pos), hits, samples };
}

function normaliseOrNot(d: ReturnType<typeof decodePreviewStreams>, tloStart: number[], basis: number[], on: boolean) {
  if (on) return normalizeToToolBasis(d, tloStart, basis);
  normalizeToToolBasis(d, tloStart, null);   // the payload as shipped
  return basis;
}

describe("tool-basis normalisation (VP-I20)", () => {
  for (const [name, pair] of Object.entries(FIXTURE.pairs as Record<string, Record<string, any>>)) {
    const [a, b] = Object.keys(pair);
    for (const [from, to] of [[a!, b!], [b!, a!]]) {
      it(`${name}: the payload at ${from} normalised to ${to} is the fresh one for every consumer`, () => {
        const fresh = pair[to]!, old = pair[from]!;
        const before = JSON.stringify(old);
        expect(consume(old, fresh.tlo_start)).toEqual(consume(fresh, fresh.tlo_start));
        expect(JSON.stringify(old), "the original data stays untouched").toBe(before);
      });
    }
  }

  it("Codex R55: the clash at Z10 is found only with the normalisation", () => {
    const { r55 } = FIXTURE.pairs;
    const fresh10 = consume(r55["10"], [0, 0, 10]);
    expect(fresh10.hits.length).toBeGreaterThan(0);
    expect(consume(r55["20"], [0, 0, 20]).hits).toEqual([]);
    // the Z20 payload resolved to basis 10 WITHOUT moving its points: no clash
    expect(consume(r55["20"], [0, 0, 10], false).hits).toEqual([]);
    expect(consume(r55["20"], [0, 0, 10]).hits).toEqual(fresh10.hits);
  });
});
