#!/usr/bin/env python3
"""Generate golden kins fixtures from the compiled LinuxCNC oracle.

TCP+TWP plan phase 1b — same discipline as gen_rs274_wcs_fixtures.py:
the oracle is the control's OWN code (scripts/kins_oracle/ vendors
trtfuncs.c + kins_util.c verbatim from v2.9.4 and compiles them for the
host), never a re-derivation. One deterministic case set pins BOTH
mirrors:

    lcnc-webui/src/viewer/kinsFixtures.gen.ts   (TS mirror tests)
    lcnc-gateway/kins_fixtures.gen.json          (Python twin tests)

Every forward case is round-tripped through the oracle's own inverse
before being written (self-consistency gate at 1e-9) — a fixture that
the oracle itself cannot reproduce is a generator bug, not a test.

Regenerate:  python3 scripts/gen_kins_fixtures.py   (needs gcc + libm)
"""
import json
import random
import subprocess
import sys
import tempfile
from pathlib import Path

SEED = 0x5C1A5
CASES_PER_DIRECTION = 20
ROUNDTRIP_TOL = 1e-9

REPO = Path(__file__).resolve().parent.parent
ORACLE = REPO / "scripts" / "kins_oracle"
TS_OUT = REPO / "lcnc-webui" / "src" / "viewer" / "kinsFixtures.gen.ts"
JSON_OUT = REPO / "lcnc-gateway" / "kins_fixtures.gen.json"

# (kins, label, xrot, yrot, zrot, xoff, yoff, zoff, tooloff)
PARAM_SETS = [
    ("xyzac", "sim-tcp",   0, 0, 0, 0, 20, 10, 0),      # lcnc_suite_sim_5axis_tcp.ini
    ("xyzac", "tool",      0, 0, 0, 0, 20, 10, 35.5),
    ("xyzac", "rot-point", 12.5, -7.25, 4, 0, 20, 10, 8.125),
    ("xyzac", "zero",      0, 0, 0, 0, 0, 0, 0),
    ("xyzbc", "basic",     0, 0, 0, 15, 0, -12, 0),
    ("xyzbc", "full",      3, 7, -2, 15, 0, -12, 21.75),
]


def compile_harness(build: Path) -> Path:
    exe = build / "harness"
    cmd = ["gcc", "-O2", "-Wall", "-I", str(ORACLE / "stub"),
           "-o", str(exe), str(ORACLE / "harness.c"), str(ORACLE / "kins_util.c"), "-lm"]
    subprocess.run(cmd, check=True)
    return exe


def run_oracle(exe: Path, kins: str, params, lines):
    args = [str(exe), kins] + [repr(float(p)) for p in params]
    r = subprocess.run(args, input="".join(lines), capture_output=True, text=True, check=True)
    out = r.stdout.splitlines()
    if len(out) != len(lines):
        sys.exit(f"oracle answered {len(out)}/{len(lines)} lines for {kins} {params}")
    return [[float(v) for v in line.split()] for line in out]


def gen_set(exe: Path, rng: random.Random, kins: str, label: str, params):
    def joints_case():
        # j3 is A (xyzac, ±100 like the sim) or B (xyzbc, -30..180 DMU-style)
        rot1 = rng.uniform(-100, 50) if kins == "xyzac" else rng.uniform(-30, 180)
        return [round(rng.uniform(-200, 200), 3) for _ in range(3)] + \
               [round(rot1, 3), round(rng.uniform(-720, 720), 3)]

    def world_case():
        rot1 = rng.uniform(-100, 50) if kins == "xyzac" else rng.uniform(-30, 180)
        w = [round(rng.uniform(-200, 200), 3) for _ in range(3)], round(rot1, 3), round(rng.uniform(-720, 720), 3)
        xyz, r1, c = w
        return xyz + ([r1, 0.0, c] if kins == "xyzac" else [0.0, r1, c])

    fwd_in = [joints_case() for _ in range(CASES_PER_DIRECTION)]
    inv_in = [world_case() for _ in range(CASES_PER_DIRECTION)]

    fwd_out = run_oracle(exe, kins, params,
                         [f"F {j[0]} {j[1]} {j[2]} {j[3]} {j[4]} 0\n" for j in fwd_in])
    inv_out = run_oracle(exe, kins, params,
                         [f"I {w[0]} {w[1]} {w[2]} {w[3]} {w[4]} {w[5]}\n" for w in inv_in])

    # Self-consistency gate: the oracle's inverse must reproduce every
    # forward case's joints from its own world output.
    rt = run_oracle(exe, kins, params,
                    [f"I {w[0]} {w[1]} {w[2]} {w[3]} {w[4]} {w[5]}\n" for w in fwd_out])
    for j_in, j_rt in zip(fwd_in, rt):
        worst = max(abs(a - b) for a, b in zip(j_in, j_rt))
        if worst > ROUNDTRIP_TOL:
            sys.exit(f"oracle self-roundtrip failed ({kins}/{label}): {worst}")

    px = ["xRotPoint", "yRotPoint", "zRotPoint", "xOffset", "yOffset", "zOffset", "toolOffset"]
    return {
        "kins": f"{kins}-trt", "label": label,
        "params": {k: float(v) for k, v in zip(px, params)},
        "forward": [{"input": i, "expect": o} for i, o in zip(fwd_in, fwd_out)],
        "inverse": [{"input": i, "expect": o} for i, o in zip(inv_in, inv_out)],
    }


def main():
    rng = random.Random(SEED)
    with tempfile.TemporaryDirectory() as td:
        exe = compile_harness(Path(td))
        sets = [gen_set(exe, rng, k, l, p) for (k, l, *p) in PARAM_SETS]

    header = (f"// AUTO-GENERATED by scripts/gen_kins_fixtures.py — DO NOT EDIT.\n"
              f"// Oracle: LinuxCNC v2.9.4 trtfuncs.c/kins_util.c compiled via\n"
              f"// scripts/kins_oracle/ (see its README for provenance). Seed {SEED:#x}.\n"
              f"// Regenerate: python3 scripts/gen_kins_fixtures.py\n")
    ts = header
    ts += ("export interface KinsFixtureCase { input: number[]; expect: number[] }\n"
           "export interface KinsFixtureSet {\n"
           "  kins: string; label: string;\n"
           "  params: { xRotPoint: number; yRotPoint: number; zRotPoint: number;\n"
           "            xOffset: number; yOffset: number; zOffset: number; toolOffset: number };\n"
           "  /** joints (5) → world [x,y,z,a,b,c] */\n"
           "  forward: KinsFixtureCase[];\n"
           "  /** world [x,y,z,a,b,c] → joints (5) */\n"
           "  inverse: KinsFixtureCase[];\n"
           "}\n"
           "export const KINS_FIXTURES: KinsFixtureSet[] = ")
    ts += json.dumps(sets, indent=1) + ";\n"
    TS_OUT.write_text(ts)

    JSON_OUT.write_text(json.dumps(
        {"generator": "scripts/gen_kins_fixtures.py", "seed": SEED,
         "oracle": "LinuxCNC v2.9.4 trtfuncs.c (scripts/kins_oracle)", "sets": sets},
        indent=1) + "\n")

    n = sum(len(s["forward"]) + len(s["inverse"]) for s in sets)
    print(f"wrote {len(sets)} sets / {n} cases -> {TS_OUT.name}, {JSON_OUT.name}")


if __name__ == "__main__":
    main()
