#!/usr/bin/env python3
"""Generate RS274 WCS-transform golden fixtures for the frontend.

Writes lcnc-webui/src/viewer/rs274Fixtures.gen.ts: a case table produced by
LinuxCNC's OWN interpreter source (rs274.interpret.Translated
.rotate_and_translate — the exact offset-application order the running
interp uses: machine = g5x + Rz(theta) . (program + g92)), plus the TLO
term (joint = machine_tip + tool_offset, XYZ) that the client transform
folds in for joint-space math.

rs274.test.ts asserts wcsTerms/programToMachine/machineToProgram reproduce
these numbers exactly, pinning the TypeScript reimplementation to the
interpreter forever. Regenerate (only on a LinuxCNC host) with:

    python3 scripts/gen_rs274_wcs_fixtures.py

Deterministic: fixed seed, no timestamps — rerunning must produce an
identical file so the checked-in fixture never churns.
"""
import json
import math
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "lcnc-gateway"))
from rs274.interpret import Translated  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..",
                   "lcnc-webui", "src", "viewer", "rs274Fixtures.gen.ts")

AXES = "xyzabcuvw"


def canon(g5x, g92, rotation_deg):
    class C:
        pass
    c = C()
    for i, ax in enumerate(AXES):
        setattr(c, f"g5x_offset_{ax}", g5x[i] if i < len(g5x) else 0.0)
        setattr(c, f"g92_offset_{ax}", g92[i] if i < len(g92) else 0.0)
    c.rotation_xy = rotation_deg
    c.rotation_cos = math.cos(math.radians(rotation_deg))
    c.rotation_sin = math.sin(math.radians(rotation_deg))
    return c


def make_case(g5x, g92, theta, tool, program):
    c = canon(g5x, g92, theta)
    m = Translated.rotate_and_translate(c, *program, 0.0, 0.0, 0.0)
    # Joint space: the servos hold tip + TLO under G43 (XYZ only — rotary
    # TLO is out of scope, matching applyState phase 3 and the gateway
    # limit check).
    joint = [m[0] + tool[0], m[1] + tool[1], m[2] + tool[2], m[3], m[4], m[5]]
    return {
        "g5x": list(g5x), "g92": list(g92), "rotationDeg": theta,
        "tool": list(tool), "program": list(program), "joint": joint,
    }


def main():
    rng = random.Random(0x5AC274)  # fixed seed — deterministic output
    cases = []

    # Edge cases first: each offset term alone, then the killer combos.
    Z6 = [0.0] * 6
    cases.append(make_case(Z6, Z6, 0.0, [0.0] * 3, (10.0, 20.0, 30.0, 40.0, 0.0, 90.0)))
    cases.append(make_case([100.0, -50.0, 25.0, 10.0, 0.0, -30.0], Z6, 0.0,
                           [0.0] * 3, (12.5, -8.0, 3.0, 15.0, 0.0, 45.0)))
    cases.append(make_case(Z6, [7.5, -3.25, 1.5, 2.0, 0.0, 5.0], 0.0,
                           [0.0] * 3, (1.0, 2.0, 3.0, 4.0, 5.0, 6.0)))
    cases.append(make_case(Z6, Z6, 30.0, [0.0] * 3, (100.0, 0.0, 0.0, 0.0, 0.0, 0.0)))
    # G92 + rotation together — the case the combined-sum model got wrong.
    cases.append(make_case([100.0, -50.0, 0.0, 0.0, 0.0, 0.0],
                           [10.0, 0.0, 0.0, 0.0, 0.0, 0.0], 30.0,
                           [0.0] * 3, (0.0, 0.0, 0.0, 0.0, 0.0, 0.0)))
    # TLO alone, and TLO + everything.
    cases.append(make_case(Z6, Z6, 0.0, [0.0, 0.0, 85.5], (5.0, 6.0, 7.0, 0.0, 0.0, 0.0)))
    cases.append(make_case([120.0, -40.0, 60.0, 5.0, 0.0, 350.0],
                           [3.0, -2.0, 1.0, 0.0, 0.0, -10.0], -22.5,
                           [0.1, -0.2, 92.75], (33.0, -44.0, 12.0, -60.0, 0.0, 540.0)))

    # Randomized sweep — broad numeric coverage, still deterministic.
    for _ in range(40):
        g5x = [round(rng.uniform(-500, 500), 4) for _ in range(6)]
        g92 = [round(rng.uniform(-50, 50), 4) for _ in range(6)]
        theta = round(rng.uniform(-180, 180), 4)
        tool = [round(rng.uniform(-5, 5), 4) for _ in range(2)] + [round(rng.uniform(0, 150), 4)]
        program = tuple(round(rng.uniform(-300, 300), 4) for _ in range(6))
        cases.append(make_case(g5x, g92, theta, tool, program))

    body = json.dumps(cases, indent=2)
    with open(OUT, "w") as f:
        f.write(
            "// GENERATED by scripts/gen_rs274_wcs_fixtures.py — DO NOT EDIT.\n"
            "// Golden fixtures from LinuxCNC's own rs274.interpret.Translated\n"
            "// .rotate_and_translate: machine = g5x + Rz(theta)*(program + g92),\n"
            "// joint = machine_tip + TLO (XYZ). rs274.test.ts pins the client\n"
            "// transform (wcsTerms/programToMachine/machineToProgram) to these.\n"
            "export interface Rs274WcsCase {\n"
            "  g5x: number[]; g92: number[]; rotationDeg: number;\n"
            "  tool: number[]; program: number[]; joint: number[];\n"
            "}\n\n"
            f"export const RS274_WCS_CASES: Rs274WcsCase[] = {body};\n"
        )
    print(f"wrote {len(cases)} cases -> {OUT}")


if __name__ == "__main__":
    main()
